In [97]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Conv2D, MaxPooling2D, Flatten
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
import numpy as np
from sklearn.model_selection import train_test_split

Encode sequences

In [104]:
def encode(infile):
    # For one-hot encoding
    d = {'A':[1,0,0,0],
        'C':[0,1,0,0],
        'G':[0,0,1,0],
        'T':[0,0,0,1]}
    f = open(infile, "r")
    X = []
    while True:
        line = f.readline()
        line = line.strip() # strip newline character
        if len(line) == 0:
            break
        seq = []
        for nt in line:
            seq.append(d[nt])
        X.append(seq)
    X = np.array(X)
    return X

In [105]:
def get_data(file1, file0, test_size=0.33):
    # One-hot encoding
    f1 = encode(file1)
    f0 = encode(file0)
    # Concatenate f1 and f0
    X = np.concatenate((f1, f0), axis=0)
    Y = np.concatenate((np.ones(len(f0)), np.zeros(len(f0))), axis=None)  # labels
    #dataset = np.concatenate((X,Y), axis=1)
    # Shuffle
    dataset = tf.data.Dataset.from_tensor_slices((X,Y))
    dataset.shuffle(buffer_size=20000)
    # Train/test splitting
    y = [y for x,y in dataset]
    #y = np.concatenate([y for x, y in dataset], axis=0)
    return y

In [108]:
y = get_data("acc.ex3.txt", "acc.not.txt")

[<tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>, <tf.Tensor: shape=(

[<tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=1.0>,


In [110]:
y[0]

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [ ]:
dataset.element_spec

In [94]:
X = encode("Ex3rearrvsNot.txt") # cds+
#x_train = encode("test.rearranged.txt")
#y_train = np.concatenate((np.ones(11360), np.zeros(11360)), axis=None)
Y = np.concatenate((np.ones(10000), np.zeros(10000)), axis=None)

In [95]:
len(X)

20000

In [87]:
x_train[0].shape

(42, 4)

Reshape so that inputs are 3D

In [88]:
x_train = np.expand_dims(x_train, axis=3)

# Check
x_train[0].shape

(42, 4, 1)

In [89]:
y_train.astype(np.uint8)

array([1, 1, 1, ..., 0, 0, 0], dtype=uint8)

In [90]:
x_train.astype(np.float64)

array([[[[1.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [0.]],

        ...,

        [[1.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [0.]],

        [[1.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [1.]],

        [[0.],
         [0.],
         [1.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [0.]],

        ...,

        [[0.],
         [1.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [0.]],

        [[1.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [1.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [1.]],

        [[0.],
         [1.],
         [0.],
         [0.]],

        ...,

        [[0.],
         

In [91]:
CNN = Sequential()

## Conv 1
CNN.add(Conv2D(64, kernel_size=(5,1), activation="relu", input_shape=x_train[0].shape)) # try other powers of 2?
#CNN.add(Dropout(0.50))
CNN.add(MaxPooling2D(pool_size=(2,1)))

## Conv 2
CNN.add(Conv2D(50, (4,2), activation='relu', kernel_regularizer=keras.regularizers.l2(1e-2)))
#CNN.add(Dropout(0.50))
CNN.add(MaxPooling2D((2, 1)))

## Conv 3
CNN.add(Conv2D(15, (4,3), activation='relu', kernel_regularizer=keras.regularizers.l2(1e-2)))
#CNN.add(Dropout(0.50))
CNN.add(MaxPooling2D((2, 1)))

CNN.add(Flatten()) # need to flatten input so it can go through dense layer
CNN.add(Dense(1, activation="sigmoid")) # 1 = exon, 0 = not  softmax does not work for binary classification

CNN.compile(loss="binary_crossentropy", # categorical_crossentropy
            optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
            metrics=["accuracy"])

In [84]:
CNN.summary()

Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_37 (Conv2D)           (None, 38, 4, 64)         384       
_________________________________________________________________
max_pooling2d_35 (MaxPooling (None, 19, 4, 64)         0         
_________________________________________________________________
conv2d_38 (Conv2D)           (None, 16, 3, 50)         25650     
_________________________________________________________________
max_pooling2d_36 (MaxPooling (None, 8, 3, 50)          0         
_________________________________________________________________
conv2d_39 (Conv2D)           (None, 5, 1, 15)          9015      
_________________________________________________________________
max_pooling2d_37 (MaxPooling (None, 2, 1, 15)          0         
_________________________________________________________________
flatten_13 (Flatten)         (None, 30)              

In [92]:
CNN.fit(x_train, y_train,
        epochs=16, 
        batch_size=256,
        shuffle=True)

Epoch 1/16
79/79 [==============================] - 9s 92ms/step - loss: 0.7607 - accuracy: 0.8329
Epoch 2/16
79/79 [==============================] - 9s 111ms/step - loss: 0.3111 - accuracy: 0.9427
Epoch 3/16
79/79 [==============================] - 8s 100ms/step - loss: 0.2244 - accuracy: 0.9675
Epoch 4/16
79/79 [==============================] - 8s 106ms/step - loss: 0.1841 - accuracy: 0.9765
Epoch 5/16
79/79 [==============================] - 7s 90ms/step - loss: 0.1640 - accuracy: 0.9792
Epoch 6/16
79/79 [==============================] - 7s 93ms/step - loss: 0.1441 - accuracy: 0.9840
Epoch 7/16
79/79 [==============================] - 8s 104ms/step - loss: 0.1333 - accuracy: 0.9842
Epoch 8/16
79/79 [==============================] - 9s 120ms/step - loss: 0.1232 - accuracy: 0.9861
Epoch 9/16
79/79 [==============================] - 7s 84ms/step - loss: 0.1142 - accuracy: 0.9871
Epoch 10/16
79/79 [==============================] - 6s 79ms/step - loss: 0.1078 - accuracy: 0.9879
Epoc

In [ ]:
'''
exons
introns
enhancers
IME: enhancer within an intron
R loops
splice sites
transcription start site
translation start site (TIS)
polyA site (PAS)
'''